openapi: 3.0.2
info:
  title: Filesystem API
  description: Filesystem API Documentation
  version: 1.0.0
servers:
  - url: 'http://localhost/api'
    description: Local server for development
paths:
  /files:
    get:
      tags:
        - File
      summary: Downlaod file by path
      description: Downloads file by path.
      responses:
        '200':
          description: File Downloaded
          content:
            text:
              schema:
                type: object
                properties:
                  path:
                    type: string
                example:
                  message: dataset/test.txt
      requestBody:
        content:
          application/json:
            schema:
              type: file

components:
  responses:
    ServerError:
      description: Server error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
            example:
              message: Server Error
    TooManyRequest:
      description: Rate limit exceeded error happens when too many requests sent. User must wait one minute.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
            example:
              message: Too Many Attempts.
    InputError:
      description: Input error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              errors:
                type: object
                items:
                  type: object
                  properties:
                    field_name:
                      type: array
                      items:
                        type: string
            example:
              message: Error message
              errors:
                field_name:
                  - Error message about field
                  - Another error message about field
    Default:
      description: Default response
      content:
        application/json: {}
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
